name: CppUnit CI (Windows)

on:
  push:
    branches: [ main dev ]
  pull_request:
    branches: [ main dev ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Настройка Visual Studio окружения
        uses: microsoft/setup-msbuild@v1.1

      - name: Сборка проекта (Debug x86)
        run: msbuild ./Plousios/UT/UT.vcxproj /p:Configuration=Debug
        
      - name: Сборка проекта (Release x86)
        run: msbuild ./Plousios/UT/UT.vcxproj /p:Configuration=Release